### PR TITLE
Setup TSLint to ensure everyone follows the same coding style

### PR DESCRIPTION
**Pull request by lanthaler**
I just chose the recommended settings but agree with [the issues TSLint raised (scroll to the end)](https://api.travis-ci.org/jobs/253362366/log.txt?deansi=true).

Once we agree on the coding style and all code adheres to it, we should move this to run `before_script` so that it fails the Travis build in case of issues.

Thoughts? @alien-mcl, what do you think about this coding style?

---
This change is [Reviewable](https://reviewable.io/reviews/hydracg/heracles.ts/10)

### CODE REVIEW

**Comment by alien-mcl** [comment]
Well, there are many schools and settings. I'm open. Indeed my style is somehow csharpyish, but I just find it more readable (i.e. than to have an opening bracket just after the signature).
Anyway, I'll walk through the issues raised and try to comply where possible.

**Comment by lanthaler** [comment]
OK. Should we merge this then or would you like to make any tweaks before doing so?

**Comment by lanthaler** [comment]
Btw. I just stumbled across https://github.com/prettier/prettier which seems to be widely used. Perhaps we should switch to it and let it reformat the code base?

**Comment by tpluscode** [comment]
Sounds good. A linter and formatter

**Comment by alien-mcl** [comment]
I'd personally leave formatting for IDE and developers and verification that would give me code style feedback for build tools.

**Comment by lanthaler** [comment]
I added a tslint-fix script and run it to make it comparable with Prettier in #12. We probably want to combine the two after looking at the result.

**Comment by lanthaler** [comment]
Please take another look. I combined TSLint and Prettier in this PR. If you write some code, in most cases you will just need to run `npm run format-code` to get all linter errors fixed. If you are using an editor which uses the TypeScript language service, you can get the linter errors shown directly in the editor. In Visual Studio Code, e.g., all you need to do is to switch to use the project's TypeScript version instead of the IDE's. You can configure this by adding the following to `.vscode/settings.json`:

```
{
    "typescript.tsdk": "node_modules\\typescript\\lib"
}
```

**Comment by elf-pavlik** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/10#-:-KvPOJANJWOju4wk9ahr:bnfp4nl)*

**Pull request merged**
