### PR TITLE
Introduced a collections helper property on IHypermediaContainer

### PR DESCRIPTION
**Pull request by alien-mcl**
As mentioned in HydraCG/Specifications#155, I've introduced a helper property to filter out all collections.

---
This change is [Reviewable](https://reviewable.io/reviews/hydracg/heracles.ts/27)

### CODE REVIEW

**Comment by lanthaler** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/DataModel/HypermediaContainer.ts, line 40 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L2vCWzc6tfuJaeLwRm_:-L2vCWzc6tfuJaeLwRma:bby7ctu) ([raw file](https://github.com/hydracg/heracles.ts/blob/e0450a9a1bdc09c4d8dc217b99d73120e8adeddc/src/DataModel/HypermediaContainer.ts#L40)):*
> control.type.contains(hydra.Collection)

What if they don't have the type set but are nevertheless referenced through the `collection` property?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/DataModel/HypermediaContainer.ts, line 40 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L2vCWzc6tfuJaeLwRm_:-L2vPMCpZbu-6kPOvcvV:b-3zl60w) ([raw file](https://github.com/hydracg/heracles.ts/blob/e0450a9a1bdc09c4d8dc217b99d73120e8adeddc/src/DataModel/HypermediaContainer.ts#L40)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> control.type.contains(hydra.Collection)

What if they don't have the type set but are nevertheless referenced through the `collection` property?
</blockquote></details>

Not sure which property do you refer to. Hydra does not define any `collection` predicate. Also the client's implementation does not have give any special meaning to such a relation. AFAIR, we agreed on explicit typing in order to get rid of any client-side type inference or reasoning processes (at least at the early stage of development).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by lanthaler** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/DataModel/HypermediaContainer.ts, line 40 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L2vCWzc6tfuJaeLwRm_:-L2xcGp3e1f843ZZwz_E:ba8s8re) ([raw file](https://github.com/hydracg/heracles.ts/blob/e0450a9a1bdc09c4d8dc217b99d73120e8adeddc/src/DataModel/HypermediaContainer.ts#L40)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Not sure which property do you refer to. Hydra does not define any `collection` predicate. Also the client's implementation does not have give any special meaning to such a relation. AFAIR, we agreed on explicit typing in order to get rid of any client-side type inference or reasoning processes (at least at the early stage of development).
</blockquote></details>

I'm referring to the `hydra:collection` property. The [entry point use case](https://github.com/HydraCG/Specifications/blob/master/drafts/use-cases/1.entry-point.md#details) shows how it is used (and here's the [issue in which we decided to introduce it](https://github.com/HydraCG/Specifications/issues/41#issuecomment-48588100))

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/DataModel/HypermediaContainer.ts, line 40 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L2vCWzc6tfuJaeLwRm_:-L3-kfJCVw51sMyztrJl:b-ce69ih) ([raw file](https://github.com/hydracg/heracles.ts/blob/e0450a9a1bdc09c4d8dc217b99d73120e8adeddc/src/DataModel/HypermediaContainer.ts#L40)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

I'm referring to the `hydra:collection` property. The [entry point use case](https://github.com/HydraCG/Specifications/blob/master/drafts/use-cases/1.entry-point.md#details) shows how it is used (and here's the [issue in which we decided to introduce it](https://github.com/HydraCG/Specifications/issues/41#issuecomment-48588100))
</blockquote></details>

Ugh. I wasn't aware of this. This issue is 4 years old and the spec has not yet been updated!

Anyway, I'm not sure whether I understand `hydra:collection` correctly. While I think I understand why `hydra:manages` is introduced (to re-assert the relation between the collection's owner and it's members, i.e. `foaf:knows`), the former's semantics is unknown to me.

It could tell the client that all resources in that relation are of type `hydra:Collection` enabling an alternative way of hooking up collections to the resources. Am I correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by lanthaler** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/DataModel/HypermediaContainer.ts, line 40 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L2vCWzc6tfuJaeLwRm_:-L3NFhLZY05xYA6QVstR:b-t89x4) ([raw file](https://github.com/hydracg/heracles.ts/blob/e0450a9a1bdc09c4d8dc217b99d73120e8adeddc/src/DataModel/HypermediaContainer.ts#L40)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Ugh. I wasn't aware of this. This issue is 4 years old and the spec has not yet been updated!

Anyway, I'm not sure whether I understand `hydra:collection` correctly. While I think I understand why `hydra:manages` is introduced (to re-assert the relation between the collection's owner and it's members, i.e. `foaf:knows`), the former's semantics is unknown to me.

It could tell the client that all resources in that relation are of type `hydra:Collection` enabling an alternative way of hooking up collections to the resources. Am I correct?
</blockquote></details>

Yes, the range of the `hydra:collection`property is `hydra:Collection`. It has very simple semantics. It just tells the client, "here are a few collections that you might be interested in too", so it's somewhat similar to `rdfs:seeAlso`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/DataModel/HypermediaContainer.ts, line 40 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L2vCWzc6tfuJaeLwRm_:-L3PBmBVa_Mb8jgffr9X:bc5on1n) ([raw file](https://github.com/hydracg/heracles.ts/blob/e0450a9a1bdc09c4d8dc217b99d73120e8adeddc/src/DataModel/HypermediaContainer.ts#L40)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Yes, the range of the `hydra:collection`property is `hydra:Collection`. It has very simple semantics. It just tells the client, "here are a few collections that you might be interested in too", so it's somewhat similar to `rdfs:seeAlso`.
</blockquote></details>

Ok - I'll add support for this. Where can I find a draft of the spec that has all the latest features?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by alien-mcl** [comment]
Review status: 3 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/DataModel/HypermediaContainer.ts, line 40 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L2vCWzc6tfuJaeLwRm_:-L3POBDwjHWkJAF27pU5:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/e0450a9a1bdc09c4d8dc217b99d73120e8adeddc/src/DataModel/HypermediaContainer.ts#L40)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Ok - I'll add support for this. Where can I find a draft of the spec that has all the latest features?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by lanthaler** [comment]
Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 47 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sVTA-7sLQBa7Nd_LI:-L3sVTA0eDdHqnbuqBMs:b-wq1t9y) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/integration-tests/server/api/context.jsonld#L47)):*
> ```JSONLD
>         },
>         "required": "hydra:required",
>         "collections": {
> ```

Please don't rename hydra properties here in the context (drop the "s" at the end) as it makes stuff unnecessarily complicated. 

---

*[src/DataModel/HypermediaContainer.ts, line 42 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sWXnKd1fkBcrChr71:-L3sWXnKd1fkBcrChr72:b-dlhjdk) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/src/DataModel/HypermediaContainer.ts#L42)):*
> entryPointCollections

This is not exclusive to entry points so you may want to rename this

---

*[src/DataModel/Collections/FilterableCollection.ts, line 64 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sVwcY7J7LLEUBRxHz:-L3sVwcY7J7LLEUBRxI-:bwrupus) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/src/DataModel/Collections/FilterableCollection.ts#L64)):*
> ```XML
>    */
>   public last(): T {
>     let result: T;
> ```

Wouldn't this return undefined as you don't initialize it to null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 47 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sVTA-7sLQBa7Nd_LI:-L4D83HvWmiL79tig18-:bbac1m2) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/integration-tests/server/api/context.jsonld#L47)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Please don't rename hydra properties here in the context (drop the "s" at the end) as it makes stuff unnecessarily complicated. 
</blockquote></details>

It was on purpose. I wanted to conceal as much of the RDF and JSON-LD as possible. Normally, I'd create a JSON structure where properties that normally would hold multiple values would end up with plural names. This is what I'm trying to do with that context.

---

*[src/DataModel/HypermediaContainer.ts, line 42 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sWXnKd1fkBcrChr71:-L4D9GpEZF52T59clD-H:b-kq485b) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/src/DataModel/HypermediaContainer.ts#L42)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> entryPointCollections

This is not exclusive to entry points so you may want to rename this
</blockquote></details>

True that - done

---

*[src/DataModel/Collections/FilterableCollection.ts, line 64 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sVwcY7J7LLEUBRxHz:-L4D9IgH-zTy3pMk1d45:b3fmduw) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/src/DataModel/Collections/FilterableCollection.ts#L64)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Wouldn't this return undefined as you don't initialize it to null?
</blockquote></details>

Oh yes. I'm wondering why my IDE complains about an unused variable initializer. Still, I'd prefer to return `null` instead of `undefined`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by lanthaler** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 47 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sVTA-7sLQBa7Nd_LI:-L4WxD0MxVeHcluKw5VY:b-mugtcp) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/integration-tests/server/api/context.jsonld#L47)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

It was on purpose. I wanted to conceal as much of the RDF and JSON-LD as possible. Normally, I'd create a JSON structure where properties that normally would hold multiple values would end up with plural names. This is what I'm trying to do with that context.
</blockquote></details>

Then this should be done consistently. All other properties are singular. E.g. `operation`, `supportedClass`, `supportedProperty`, ... To keep changes at a manageable level in this PR I'd suggest keep this singular as well for now and if really desired switch to plural everywhere in a subsequent PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 47 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sVTA-7sLQBa7Nd_LI:-L4XCRzaIWFvjSoGwopi:b-uz3uhd) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/integration-tests/server/api/context.jsonld#L47)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Then this should be done consistently. All other properties are singular. E.g. `operation`, `supportedClass`, `supportedProperty`, ... To keep changes at a manageable level in this PR I'd suggest keep this singular as well for now and if really desired switch to plural everywhere in a subsequent PR.
</blockquote></details>

True that. I believe this was due to fact those you mentioned were added at the very beginning `automatically` as we're not using them in any way for the time being. Still, I'd update those to plural if that's OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by alien-mcl** [comment]
Can we move on with this PR?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-:-L5Q6b-fjO6FmNFRdjL0:b6d7y92)*

**Comment by tpluscode** [comment]
Reviewed 1 of 5 files at r1, 2 of 12 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/DataModel/HypermediaContainer.ts, line 45 at r3](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L6qFMsuwSLsLF84kDIq:-L6qFMsvhO1LXZjumiYB:b-iv4uiu) ([raw file](https://github.com/hydracg/heracles.ts/blob/f73bc553efaaf948b6a7bc6e31ed624cc3a8fa0b/src/DataModel/HypermediaContainer.ts#L45)):*
> ```XML
>       itemsArray
>         .filter(control => !!(control as any).collections)
>         .map(control => Array.from((control as any).collections) as ICollection[])[0] || [];
> ```

Could you explain `availableCollections`? I don't understand from the code

---

*[src/DataModel/IHydraResource.ts, line 17 at r3](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L6qGWzaMf0nWH6lKOE0:-L6qGWzb1MfahO4iVJ6O:bu47prg) ([raw file](https://github.com/hydracg/heracles.ts/blob/f73bc553efaaf948b6a7bc6e31ed624cc3a8fa0b/src/DataModel/IHydraResource.ts#L17)):*
> ```XML
>    * @returns {ResourceFilterableCollection<ICollection>}
>    */
>   readonly collections: ResourceFilterableCollection<ICollection>;
> ```

Do we really want `hydra:collection` on every resource? It strikes me as odd on templated link...

---

*[src/DataModel/Collections/FilterableCollection.ts, line 65 at r3](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L6qGtPZ8WP7F_CbuuPT:-L6qGtPZ8WP7F_CbuuPU:besljom) ([raw file](https://github.com/hydracg/heracles.ts/blob/f73bc553efaaf948b6a7bc6e31ed624cc3a8fa0b/src/DataModel/Collections/FilterableCollection.ts#L65)):*
> ```XML
>   public last(): T {
>     let result: T = null;
>     for (const item of this) {
> ```

Call it premature optimisation but looping over the items seems a bit inefficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/DataModel/HypermediaContainer.ts, line 45 at r3](https://beta.reviewable.io/reviews/hydracg/heracles.ts/27#-L6qFMsuwSLsLF84kDIq:-L710Ie14ytV_E4q46x0:b9k0ukb) ([raw file](https://github.com/hydracg/heracles.ts/blob/f73bc553efaaf948b6a7bc6e31ed624cc3a8fa0b/src/DataModel/HypermediaContainer.ts#L45)):*
<details><summary><i>Previously, tpluscode (Tomasz Pluskiewicz) wrote…</i></summary><blockquote>

Could you explain `availableCollections`? I don't understand from the code
</blockquote></details>

I've updated code to be clearer about it. Hope it helps.

---

*[src/DataModel/IHydraResource.ts, line 17 at r3](https://beta.reviewable.io/reviews/hydracg/heracles.ts/27#-L6qGWzaMf0nWH6lKOE0:-L710PhlC-h_QlD9NjGn:b65vy31) ([raw file](https://github.com/hydracg/heracles.ts/blob/f73bc553efaaf948b6a7bc6e31ed624cc3a8fa0b/src/DataModel/IHydraResource.ts#L17)):*
<details><summary><i>Previously, tpluscode (Tomasz Pluskiewicz) wrote…</i></summary><blockquote>

Do we really want `hydra:collection` on every resource? It strikes me as odd on templated link...
</blockquote></details>

This interface is considered as an equivalent of `hydra:Resource` class. It currently has a `hydra:operation` predicate, thus `operation` property is created. But if the operations are available I see no objection to having also `links` exposed here. And if `links` are exposed, why not exposing `collections` separately.
Indeed, in many places these will be empty collections, but API user won't have to property-check on every attempt to access these.
I'm still opened on discussion which interfaces should extend `IHydraResource` though so we can get rid of some of these properties here and there.

---

*[src/DataModel/Collections/FilterableCollection.ts, line 65 at r3](https://beta.reviewable.io/reviews/hydracg/heracles.ts/27#-L6qGtPZ8WP7F_CbuuPT:-L7126Fg0tNCidMih8_1:b-7567vp) ([raw file](https://github.com/hydracg/heracles.ts/blob/f73bc553efaaf948b6a7bc6e31ed624cc3a8fa0b/src/DataModel/Collections/FilterableCollection.ts#L65)):*
<details><summary><i>Previously, tpluscode (Tomasz Pluskiewicz) wrote…</i></summary><blockquote>

Call it premature optimisation but looping over the items seems a bit inefficient.
</blockquote></details>

Hmm. This is not an Array, thus I cannot get the item at the `array.length - 1`.  Also using Array.from will iterate all items. I see no other approach here that won't incorporate full iteration over all whole collection.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/27)*

**Comment by lanthaler** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 47 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sVTA-7sLQBa7Nd_LI:-L7TNbJgK_34NvHAqTsy:b-mlrya4) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/integration-tests/server/api/context.jsonld#L47)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

True that. I believe this was due to fact those you mentioned were added at the very beginning `automatically` as we're not using them in any way for the time being. Still, I'd update those to plural if that's OK.
</blockquote></details>

I'd prefer them to be exactly the same as in the Hydra vocab but as long as it is consistent I'm fine either way.

---

*[src/DataModel/HypermediaContainer.ts, line 45 at r3](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L6qFMsuwSLsLF84kDIq:-L7TNNBCm0EIDxauOjtM:b3kqlvv) ([raw file](https://github.com/hydracg/heracles.ts/blob/f73bc553efaaf948b6a7bc6e31ed624cc3a8fa0b/src/DataModel/HypermediaContainer.ts#L45)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

I've updated code to be clearer about it. Hope it helps.
</blockquote></details>

@tpluscode can we resolve this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by tpluscode** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-:-L7ppMguBYtNhoGHdzYx:bnfp4nl)*

**Comment by lanthaler** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 47 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sVTA-7sLQBa7Nd_LI:-L7tv_7PEX1pSUvjklVJ:bjvp3hz) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/integration-tests/server/api/context.jsonld#L47)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

I'd prefer them to be exactly the same as in the Hydra vocab but as long as it is consistent I'm fine either way.
</blockquote></details>

Karol. This is the only comment left. Would be nice to move on with this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 47 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/27#-L3sVTA-7sLQBa7Nd_LI:-L7uO_QNKMc-469Dp-Xu:b6x2u65) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/integration-tests/server/api/context.jsonld#L47)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Karol. This is the only comment left. Would be nice to move on with this
</blockquote></details>

Ugh - sorry, I missed that one. Done - it is as in the vocab now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/27)*

**Comment by lanthaler** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 47 at r2](https://beta.reviewable.io/reviews/hydracg/heracles.ts/27#-L3sVTA-7sLQBa7Nd_LI:-L8qmTHvBWhykwlRRMe7:b-zcjvte) ([raw file](https://github.com/hydracg/heracles.ts/blob/7a9184c87e7906a03377acfb7a1b077fd580d6f7/integration-tests/server/api/context.jsonld#L47)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Ugh - sorry, I missed that one. Done - it is as in the vocab now.
</blockquote></details>

Thanks

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/27)*

**Comment by lanthaler** [comment]
Please resolve the merge conflicts

**Comment by lanthaler** [comment]
Reviewed 1 of 9 files at r6.
Review status: 8 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/27)*

**Comment by lanthaler** [comment]
Reviewed 5 of 9 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/27)*

**Pull request merged**
