### PR TITLE
Implementation of two new API documentation use cases 2.1 and 2.2

### PR DESCRIPTION
**Pull request by alien-mcl**
Please find the attached PR for two new API documentation use cases:
- [2.1 API Documentation data structures](https://github.com/HydraCG/Specifications/blob/master/drafts/use-cases/2.1.api-documentation-data-structures.md)
- [2.2 API Documentation user document](https://github.com/HydraCG/Specifications/blob/master/drafts/use-cases/2.2.api-documentation-user-document.md)

It also implements a simple indirect typing mechanism for internal data model.

---
This change is [Reviewable](https://reviewable.io/reviews/hydracg/heracles.ts/30)

### CODE REVIEW

**Comment by alien-mcl** [comment]
Can we proceed with this one? I've got feature ready using this PR awaiting.

**Comment by lanthaler** [comment]
Reviewed 25 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[integration-tests/HydraClient.ApiDocumentation.spec.ts, line 22 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qsY82CCrELrH6dwGq:-L8qsY82CCrELrH6dwGr:b-ctb48) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/integration-tests/HydraClient.ApiDocumentation.spec.ts#L22)):*
> ```XML
>     describe("and obtaining it's API documentation as in use case 2.api-documentation", () => {
>       it("should obtain an API documentation", () => {
>         expect(this.apiDocumentation).not.toBeNull();
> ```

This test won't fail if `this.apiDocumentation` is `undefined`. I'd suggest to either use `.toEqual(jasmine.any(ApiDocumentation))` or at least `.toBeTruthy()`.

---

*[integration-tests/server/api/context.jsonld, line 12 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qpY6m8HP5K5V4yhT-:-L8qpY6m8HP5K5V4yhT0:b-ncsj31) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/integration-tests/server/api/context.jsonld#L12)):*
> ```
> description": "rdfs:comment
> ```

We should keep description for `hydra:description`. I'd suggest to use Hydra's title and description instead (also change label to title in `documentation.jsonld`)

---

*[src/IHydraClient.ts, line 18 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qqUe69noCpTZNrz2S:-L8qqUe69noCpTZNrz2T:bogqhjz) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/IHydraClient.ts#L18)):*
> ```XML
>    * @param response Raw response to find hypermedia processor for.
>    */
>   getHypermediaProcessor(response: Response): IHypermediaProcessor;
> ```

Why would an application need to know about hypermedia processors? Shouldn't that be an implementation detail?

---

*[src/JsonLd/IPropertyMapping.ts, line 7 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qr9-U3IrJa3_TCK0S:-L8qr9-U3IrJa3_TCK0T:b-kbz27n) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/JsonLd/IPropertyMapping.ts#L7)):*
> ```
> mappings used in
> ```

--> mapping in

---

*[src/JsonLd/isOfType.ts, line 5 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qrTPVATX0DGJkuQxU:-L8qrTPVATX0DGJkuQxV:bgbdr47) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/JsonLd/isOfType.ts#L5)):*
> ```XML
> 
> const propertyDomain = {};
> propertyDomain[hydra.entrypoint] = hydra.ApiDocumentation;
> ```

I think it would be better to just retrieve the Hydra vocab and extract the information from there.

---

*[tests/JsonLd/input.json, line 19 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qs8bn-kL057nPjf96:-L8qs8bn-kL057nPjf97:b-1vx1db) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/tests/JsonLd/input.json#L19)):*
> ```JSON
>                 "api:closed-events": "http://temp.uri/api/events/closed",
>                 "hydra:search": {
>                     "hydra:template": "http://temp.uri/api/events{?searchPhrase}",
> ```

Why did you remove the type? I think we should see it as best practice to explicitly type resources.

Also, the `@id` below shouldn't be necessary.

---

*[integration-tests/HydraClient.EntryPoint.spec.ts, line 9 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qpEI43aL_EL0oMvca:-L8qpEI43aL_EL0oMvcb:b-wz8re0) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/integration-tests/HydraClient.EntryPoint.spec.ts#L9)):*
> ```XML
> describe("Having a Hydra client", () => {
>   beforeEach(() => {
>     jasmine.addMatchers({ toBeLike: () => new HydraResourceMatcher() });
> ```

Doesn't seem to be used

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[integration-tests/HydraClient.ApiDocumentation.spec.ts, line 22 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qsY82CCrELrH6dwGq:-L8sJzXe1jHC_MB1HBu8:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/integration-tests/HydraClient.ApiDocumentation.spec.ts#L22)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

This test won't fail if `this.apiDocumentation` is `undefined`. I'd suggest to either use `.toEqual(jasmine.any(ApiDocumentation))` or at least `.toBeTruthy()`.
</blockquote></details>

Done.

---

*[integration-tests/server/api/context.jsonld, line 12 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qpY6m8HP5K5V4yhT-:-L8sKCr6DMdIel-ptCMH:brm7zl8) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/integration-tests/server/api/context.jsonld#L12)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> ```
> description": "rdfs:comment
> ```

We should keep description for `hydra:description`. I'd suggest to use Hydra's title and description instead (also change label to title in `documentation.jsonld`)
</blockquote></details>

Are we sure about this? I remember discussions and several people pointed that they were using more generic predicates rather those from hydra. To be honest, I usually do the same.

---

*[src/IHydraClient.ts, line 18 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qqUe69noCpTZNrz2S:-L8sKpy3DsvhRyanPi0U:blp80jk) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/IHydraClient.ts#L18)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Why would an application need to know about hypermedia processors? Shouldn't that be an implementation detail?
</blockquote></details>

I think this could be useful to determine what request/response options client has. I imagine various RDF formats flying here and there, I'd like to give developers change to discover these capabilities.
Currently we're not using it for invoking operations, but we actually should use either hypermedia processor that knows what kind of media type it supports or some other interface that does the opposite to the one mentioned.

---

*[src/JsonLd/IPropertyMapping.ts, line 7 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qr9-U3IrJa3_TCK0S:-L8sLXAF9ZOklD4uqyiP:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/JsonLd/IPropertyMapping.ts#L7)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> ```
> mappings used in
> ```

--> mapping in
</blockquote></details>

Done.

---

*[src/JsonLd/isOfType.ts, line 5 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qrTPVATX0DGJkuQxU:-L8sLh0i654XyerpKejR:bsnnmw7) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/JsonLd/isOfType.ts#L5)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

I think it would be better to just retrieve the Hydra vocab and extract the information from there.
</blockquote></details>

Do you mean obtain the JSON-LD vocab dynamically or embed it statically here?

---

*[tests/JsonLd/input.json, line 19 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qs8bn-kL057nPjf96:-L8sM2Gm2x7SKutsBDk5:bpgb0oe) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/tests/JsonLd/input.json#L19)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Why did you remove the type? I think we should see it as best practice to explicitly type resources.

Also, the `@id` below shouldn't be necessary.
</blockquote></details>

I needed a test case for indirect typing implementation.
As for the `@id` - it is, with the current context at least. Otherwise it expands to `@value`. 

Speaking of best practices - I see explicit typing of _intermediate/temporary_ resources like those in `hydra:mapping` cumbersome. Personally I don't care whether the resource being in relation of `hydra:mapping` is of type `hydra:IriTemplateMapping` or some other - I just need it for the time beeing.
I agree that client shouldn't be forced neither to advanced type entailing nor reasoning, but my common sense tells me that some simple cases should be covered.

---

*[integration-tests/HydraClient.EntryPoint.spec.ts, line 9 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qpEI43aL_EL0oMvca:-L8sK6169NTqT2HpvOW4:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/integration-tests/HydraClient.EntryPoint.spec.ts#L9)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Doesn't seem to be used
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30)*

**Comment by lanthaler** [comment]
Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 12 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qpY6m8HP5K5V4yhT-:-L90V1D56C7SUuVHvXEa:b-rke692) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/integration-tests/server/api/context.jsonld#L12)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Are we sure about this? I remember discussions and several people pointed that they were using more generic predicates rather those from hydra. To be honest, I usually do the same.
</blockquote></details>

Given that this is a Hydra library and Hydra has those terms, I think we should use them. Ideally, I think we should prefer the Hydra terms and fall back to the RDFS or Schema.org ones if we don't find the Hydra terms.

---

*[src/IHydraClient.ts, line 18 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qqUe69noCpTZNrz2S:-L90WFJPDSqBsEsHbYCo:bgx4woe) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/IHydraClient.ts#L18)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

I think this could be useful to determine what request/response options client has. I imagine various RDF formats flying here and there, I'd like to give developers change to discover these capabilities.
Currently we're not using it for invoking operations, but we actually should use either hypermedia processor that knows what kind of media type it supports or some other interface that does the opposite to the one mentioned.
</blockquote></details>

I generally follow the rule to not expose anything till it is absolutely needed. This keeps APIs simpler and allows to change things along the way without breaking users.

I'll leave it up to you to decide whether this is needed (at this stage)

---

*[src/JsonLd/isOfType.ts, line 5 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qrTPVATX0DGJkuQxU:-L90VWq126WY3HP40HC1:bfgq07i) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/JsonLd/isOfType.ts#L5)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Do you mean obtain the JSON-LD vocab dynamically or embed it statically here?
</blockquote></details>

The former... but I could also live with the latter for the time being

---

*[tests/JsonLd/input.json, line 19 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qs8bn-kL057nPjf96:-L90VyMJBZWpG1HTRmev:bhuhurr) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/tests/JsonLd/input.json#L19)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

I needed a test case for indirect typing implementation.
As for the `@id` - it is, with the current context at least. Otherwise it expands to `@value`. 

Speaking of best practices - I see explicit typing of _intermediate/temporary_ resources like those in `hydra:mapping` cumbersome. Personally I don't care whether the resource being in relation of `hydra:mapping` is of type `hydra:IriTemplateMapping` or some other - I just need it for the time beeing.
I agree that client shouldn't be forced neither to advanced type entailing nor reasoning, but my common sense tells me that some simple cases should be covered.
</blockquote></details>

I see.

Sorry, looks like I assumed you use the same context everywhere. I should have checked.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 12 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qpY6m8HP5K5V4yhT-:-L92ABfn4pIVwFdnawtk:b-536r0p) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/integration-tests/server/api/context.jsonld#L12)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Given that this is a Hydra library and Hydra has those terms, I think we should use them. Ideally, I think we should prefer the Hydra terms and fall back to the RDFS or Schema.org ones if we don't find the Hydra terms.
</blockquote></details>

I understand this - but do we really need those in hydra after all.

---

*[src/IHydraClient.ts, line 18 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qqUe69noCpTZNrz2S:-L92A_N34iGicEueTB0F:b63lj5i) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/IHydraClient.ts#L18)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

I generally follow the rule to not expose anything till it is absolutely needed. This keeps APIs simpler and allows to change things along the way without breaking users.

I'll leave it up to you to decide whether this is needed (at this stage)
</blockquote></details>

I was just wondering about HTTP 300 Multiple Choices - how would a developer choose which version to pick not knowing what the client supported?

---

*[src/JsonLd/isOfType.ts, line 5 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qrTPVATX0DGJkuQxU:-L92BF2T544_gPfhAHz3:blul1t1) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/JsonLd/isOfType.ts#L5)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

The former... but I could also live with the latter for the time being
</blockquote></details>

I though so - this is not a 5 mins change so I'll need some more time for this to accomplish (and make tests invulnerable to possible future Hydra JSON-LD context changes).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[integration-tests/server/api/context.jsonld, line 12 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qpY6m8HP5K5V4yhT-:-L9RLSzz3UewSXWFmon_:b6wcqc0) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/integration-tests/server/api/context.jsonld#L12)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

I understand this - but do we really need those in hydra after all.
</blockquote></details>

OK. I've made a change so resources of type`rdf:Property` are using `rdfs:label` and `rdfs:comments`, resources of type `hydra:ApiDocumentation` and `hydra:Class` are using `hydra:title` and `hydra:description`.

---

*[src/JsonLd/isOfType.ts, line 5 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qrTPVATX0DGJkuQxU:-L9RLuxl9DwEA2odgd1C:b4q4p0k) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/JsonLd/isOfType.ts#L5)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

I though so - this is not a 5 mins change so I'll need some more time for this to accomplish (and make tests invulnerable to possible future Hydra JSON-LD context changes).
</blockquote></details>

I've introduced some components that can be fed with ontologies. For now I've made `hydra` ontology embedded statically as a file (it was quicker that way), but I'll replace it with dynamically loaded one from hydra namespace.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30)*

**Comment by alien-mcl** [comment]
@lanthaler, @elf-pavlik, @tpluscode - I've updated this PR with master merge so it can be auto-merged, but can wee proceed with this one?

---

Review status: 8 of 30 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-:-L9lAZ1648tfZq1rcK3h:b55tftu)*

**Comment by lanthaler** [comment]
:lgtm:

---

Reviewed 24 of 26 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 6 at r3](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-LA9789hD5wNoL2xIHuJ:-LA9789hD5wNoL2xIHuK:bcrd80e) ([raw file](https://github.com/hydracg/heracles.ts/blob/72f9af27e3cc0cf98dbf6b1187e65be3dfbd67d0/package.json#L6)):*
> ```JSON
>   "contributors": [
>       { "name": "Markus Lanthaler" },
>       { "name": "Karol Szczepanski" },
> ```

You should definitely put your name in the first position

---

*[src/IHydraClient.ts, line 18 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qqUe69noCpTZNrz2S:-LA992-9BEtQkGOImL3n:b-q72sua) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/IHydraClient.ts#L18)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

I was just wondering about HTTP 300 Multiple Choices - how would a developer choose which version to pick not knowing what the client supported?
</blockquote></details>

I'm not sure I follow...

---

*[src/JsonLd/IOntologyProvider.ts, line 5 at r3](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-LA97scV0PWfOS0Vza_C:-LA97scV0PWfOS0Vza_D:b-5bj9j7) ([raw file](https://github.com/hydracg/heracles.ts/blob/72f9af27e3cc0cf98dbf6b1187e65be3dfbd67d0/src/JsonLd/IOntologyProvider.ts#L5)):*
> ```XML
>  * @interface
>  */
> export interface IOntologyProvider {
> ```

Purely a matter of a taste but I'd try to avoid using the term "ontology". It scares people off. Vocabulary is a fine and widely understood alternative.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-:-LA995HEBbyYvcQ2YrsD:bnfp4nl)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 6 at r3](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-LA9789hD5wNoL2xIHuJ:-LA9W4pQ1MCw_OhtB3Wj:bs7wmnj) ([raw file](https://github.com/hydracg/heracles.ts/blob/72f9af27e3cc0cf98dbf6b1187e65be3dfbd67d0/package.json#L6)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

You should definitely put your name in the first position
</blockquote></details>

OK. I won't argue with that :)

---

*[src/IHydraClient.ts, line 18 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qqUe69noCpTZNrz2S:-LA9WBwkE1s1r_eCy09S:bbebns2) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/IHydraClient.ts#L18)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

I'm not sure I follow...
</blockquote></details>

I envision a situation, when a Hydra client makes a request, but server returns back with HTTP 300 Multiple Choices. It is not yet available, but I'd expect a client exposes i.e. an event or callback which would allow developer to decide on how to proceed, i.e. by comparing what currently client is capable of with what server provided.

---

*[src/JsonLd/IOntologyProvider.ts, line 5 at r3](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-LA97scV0PWfOS0Vza_C:-LA9XtBbBSSl5eyBxn2g:bvzeasu) ([raw file](https://github.com/hydracg/heracles.ts/blob/72f9af27e3cc0cf98dbf6b1187e65be3dfbd67d0/src/JsonLd/IOntologyProvider.ts#L5)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Purely a matter of a taste but I'd try to avoid using the term "ontology". It scares people off. Vocabulary is a fine and widely understood alternative.
</blockquote></details>

Agree - done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30)*

**Comment by lanthaler** [comment]
Reviewed 23 of 29 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/IHydraClient.ts, line 18 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30#-L8qqUe69noCpTZNrz2S:-LAEqesY7HmuL_Rp_hry:b-u7reqc) ([raw file](https://github.com/hydracg/heracles.ts/blob/92b7e82d6b2c241a5d0044ef5a7c2a5b96d80fbd/src/IHydraClient.ts#L18)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

I envision a situation, when a Hydra client makes a request, but server returns back with HTTP 300 Multiple Choices. It is not yet available, but I'd expect a client exposes i.e. an event or callback which would allow developer to decide on how to proceed, i.e. by comparing what currently client is capable of with what server provided.
</blockquote></details>

As discussed on the call today, let's not block the PR on this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/30)*

**Pull request merged**
