### PR TITLE
Implementation of the use case 8.filtering-events

### PR DESCRIPTION
**Pull request by alien-mcl**
Please find the implementation of the use case where an arbitrarily pointed templated operation is used for filtering.
I've introduced template mapping via a builder.

---
This change is [Reviewable](https://reviewable.io/reviews/hydracg/heracles.ts/29)

### CODE REVIEW

**Comment by lanthaler** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/HydraClient.spec.ts, line 123 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/29#-L3NJmqMtcygpwKmB0av:-L3NJmqMtcygpwKmB0aw:b-h2ef0f) ([raw file](https://github.com/hydracg/heracles.ts/blob/9427299bb92bca070aace8af501ae1d09c68f4eb/integration-tests/HydraClient.spec.ts#L123)):*
> http://example.com/vocab#filter

The use case doc uses `hydra:search`. Why do you introduce your own filter property here?

---

*[src/DataModel/IPointingResource.ts, line 8 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/29#-L3NKEY8O4OrLsAC9EUg:-L3NKEY8O4OrLsAC9EUh:bhp0k8w) ([raw file](https://github.com/hydracg/heracles.ts/blob/9427299bb92bca070aace8af501ae1d09c68f4eb/src/DataModel/IPointingResource.ts#L8)):*
> IPointingResource

What do you try to say with this? Why didn't you just call it a "link"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/29)*

**Comment by alien-mcl** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/HydraClient.spec.ts, line 123 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/29#-L3NJmqMtcygpwKmB0av:-L3PCv_ded7hp6LhNDeU:br990v3) ([raw file](https://github.com/hydracg/heracles.ts/blob/9427299bb92bca070aace8af501ae1d09c68f4eb/integration-tests/HydraClient.spec.ts#L123)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> http://example.com/vocab#filter

The use case doc uses `hydra:search`. Why do you introduce your own filter property here?
</blockquote></details>

I didn't want to extend a built-in `hydra:search` including`hydra:freetextQuery`with other properties. While the [use case](https://github.com/HydraCG/Specifications/blob/master/drafts/use-cases/8.filtering-events.md) described uses `search`, the purpose of this use case was to enable clients to discover various custom filters with explicitly defined properties, i.e. events filtered by it's date, etc.

---

*[src/DataModel/IPointingResource.ts, line 8 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/29#-L3NKEY8O4OrLsAC9EUg:-L3PDbEDziivVk-1XtW6:b-72wuc2) ([raw file](https://github.com/hydracg/heracles.ts/blob/9427299bb92bca070aace8af501ae1d09c68f4eb/src/DataModel/IPointingResource.ts#L8)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> IPointingResource

What do you try to say with this? Why didn't you just call it a "link"?
</blockquote></details>

I wanted to leave `ILink` as an equivalent of the `hydra:Link`. This interface has a target URL, which `hydra:Link` is missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/29)*

**Comment by alien-mcl** [comment]
It looks like this PR got stuck - can we move on?

---

Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/29#-:-L4D7vhRMFSONbS22gGX:b8dyj0f)*

**Comment by lanthaler** [comment]
Let's discuss it in tomorrow's telecon. I added it to the agenda: https://www.w3.org/community/hydra/wiki/Conference_Calls#2018-02-05

---

Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/HydraClient.spec.ts, line 123 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/29#-L3NJmqMtcygpwKmB0av:-L4WvpWQjJzNs3rQL80T:b-jxu2pp) ([raw file](https://github.com/hydracg/heracles.ts/blob/9427299bb92bca070aace8af501ae1d09c68f4eb/integration-tests/HydraClient.spec.ts#L123)):*
> Implementation of the use case 8.filtering-events

Then we should change the test's and the PR's description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/29#-:-L4WvwUWWjgFe8Z9IR4o:b-c2kao3)*

**Comment by alien-mcl** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/HydraClient.spec.ts, line 123 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/29#-L3NJmqMtcygpwKmB0av:-L4XCqh4thkZsF4obXA8:b-4xnydp) ([raw file](https://github.com/hydracg/heracles.ts/blob/9427299bb92bca070aace8af501ae1d09c68f4eb/integration-tests/HydraClient.spec.ts#L123)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> Implementation of the use case 8.filtering-events

Then we should change the test's and the PR's description.
</blockquote></details>

Hmm. I'm not sure why. Both use case and the brief mentions filtering rather than searching (which was use case 7). Also the test mentions filtering results rather than search results.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/29)*

**Comment by alien-mcl** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[integration-tests/HydraClient.spec.ts, line 123 at r1](https://beta.reviewable.io/reviews/hydracg/heracles.ts/29#-L3NJmqMtcygpwKmB0av:-L4baOpJ273EPyxrl6Tj:be74xh4) ([raw file](https://github.com/hydracg/heracles.ts/blob/9427299bb92bca070aace8af501ae1d09c68f4eb/integration-tests/HydraClient.spec.ts#L123)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Hmm. I'm not sure why. Both use case and the brief mentions filtering rather than searching (which was use case 7). Also the test mentions filtering results rather than search results.
</blockquote></details>

OK - I've changed it so it should fit it better as agreed on the call.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/29)*

**Comment by lanthaler** [comment]
:lgtm:

---

Reviewed 18 of 19 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/hydracg/heracles.ts/29#-:-L4eC8sj9ZwMToIB4NTx:bnfp4nl)*

**Pull request merged**
