### PR TITLE
Use cases/7.searching events

### PR DESCRIPTION
**Pull request by alien-mcl**
Please find the attached implementation of the use case 7 related to searching events.
This implementation introduces new hydra resource member named `links` which should contain given resource's links.

---
This change is [Reviewable](https://reviewable.io/reviews/hydracg/heracles.ts/23)

### CODE REVIEW

**Comment by lanthaler** [comment]
Cool. How would this work if a response has nested resources? Something like

```
{
  "@id": "markus",
  "@type": "Person",
  "homepage": "http://....",
  "knows": {
    "@id": "karol",
    "@type": "Person",
    "homepage": "http://...."
   }
}
```

Here we have two `homepage` and one `knows` link.

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/DataModel/ILink.ts, line 4 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mQvKk7CRx2EN-REi5:-L1mQvKk7CRx2EN-REi6:b-wmz5j3) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/ILink.ts#L4)):*
> ```XML
> 
> /**
>  * Provides a link that can has an URI template.
> ```

Do you mean "that can be used as an URI template" or "can be a URI template"?

I would also change this to IRI template for consistency

---

*[src/DataModel/ITemplatedOperation.ts, line 4 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mRLcF_3q24aoMXjOY:-L1mRLcF_3q24aoMXjOZ:b-eig4cn) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/ITemplatedOperation.ts#L4)):*
> has 

Is grammatically incorrect here. It should be "have". Using a different verb such as "point to" might make this clearer though.

---

*[src/DataModel/TemplatedLink.ts, line 54 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mS0KCAQnW1gpA774q:-L1mS0KCAQnW1gpA774r:b-gi6dka) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/TemplatedLink.ts#L54)):*
> ```XML
>     return {
>       baseUrl: this.baseUrl,
>       iri: `_:blankLink${++TemplatedLink.id}`,
> ```

This seems a bit weird to me. We should either leave this untouched or *only* return the expanded target (perhaps as a non-templated ILink). I think I'd prefer the latter.

---

*[src/DataModel/TemplatedOperation.ts, line 35 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mSktRjGsqO0y10xNp:-L1mSktRjGsqO0y10xNq:b-ctmhj3) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/TemplatedOperation.ts#L35)):*
> ```XML
>   public readonly operations: OperationsCollection;
> 
>   public readonly links: LinksCollection;
> ```

Why do we need this collection here? 

---

*[src/JsonLd/linksExtractor.ts, line 15 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mTZvhqE673wSg2nmP:-L1mTZvhqE673wSg2nmQ:b-o7dl4q) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/JsonLd/linksExtractor.ts#L15)):*
> context

This is not a JSON-LD context, right? Could we use a different term?

---

*[src/JsonLd/linksExtractor.ts, line 20 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mTqS5KcHwO9SmWBLE:-L1mTqS5KcHwO9SmWBLF:bjqsnwm) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/JsonLd/linksExtractor.ts#L20)):*
> ```XML
>   for (const predicate of Object.keys(originalResource)) {
>     let linkType = hydraLinks[predicate] || null;
>     if (!linkType) {
> ```

Why do you restrict this to the handful Hydra link relation types? Wouldn't it be simpler to treat everything the same way?

---

*[src/JsonLd/operationsExtractor.ts, line 6 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mUeBnQ_ke10Ja-S5U:-L1mUeBnQ_ke10Ja-S5V:b-rhjuvr) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/JsonLd/operationsExtractor.ts#L6)):*
> operationsExtractor

Doesn't seem to be a generic operations extractor. Should we rename to reflect what it does?

---

*[tests/DataModel/TemplatedLink.spec.ts, line 19 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mVY03OgSUg0PBKwqy:-L1mVY03OgSUg0PBKwqz:buo242i) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/tests/DataModel/TemplatedLink.spec.ts#L19)):*
> hydra.Link, hydra.TemplatedLink

hydra:TemplatedLink is *not* a subclass of hydra:Link. In fact, they need to be disjoint classes as otherwise a client wouldn't know whether it should follow `@id` or `template`

---

*[tests/DataModel/Collections/LinksCollection.spec.ts, line 6 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mW3wi82wzm_WOW6iQ:-L1mW3wj53S0b3sn6Opk:b-jy85cq) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/tests/DataModel/Collections/LinksCollection.spec.ts#L6)):*
> iri: "LinkType1", type: [hydra.Link] 

Making this `type: "LinkType1"` or at least `relationType: "LinkType1"` would seem like a cleaner design to me. Also, since tests often double as documentation should we add the targets to these links?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-:-L1mXE84AaspV5EStFzr:b-ro5lqa)*

**Comment by alien-mcl** [comment]
I'll try to add some tests for nested resources. Generally speaking - it should work as the JSON-LD decomposition is recursive.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/DataModel/ILink.ts, line 4 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mQvKk7CRx2EN-REi5:-L26plDdzjqSvkQ8GkSf:b-50f7q1) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/ILink.ts#L4)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Do you mean "that can be used as an URI template" or "can be a URI template"?

I would also change this to IRI template for consistency
</blockquote></details>

Yep, this is an incorrect description. There is no URI template available here at all.

---

*[src/DataModel/ITemplatedOperation.ts, line 4 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mRLcF_3q24aoMXjOY:-L26q-e7GDMNyMeT_gfa:b-jyvyhl) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/ITemplatedOperation.ts#L4)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> has 

Is grammatically incorrect here. It should be "have". Using a different verb such as "point to" might make this clearer though.
</blockquote></details>

OK, to be fixed.

---

*[src/DataModel/TemplatedLink.ts, line 54 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mS0KCAQnW1gpA774q:-L26q93AsC3yBlSYCT9e:b-2xjbdx) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/TemplatedLink.ts#L54)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

This seems a bit weird to me. We should either leave this untouched or *only* return the expanded target (perhaps as a non-templated ILink). I think I'd prefer the latter.
</blockquote></details>

Not sure which part of the code is commented, but generally this is what you mentioned - static ILink compatible object with flat target. As for the _iri_ - again it is generanet from scratch as it is no more the original templated link.

---

*[src/DataModel/TemplatedOperation.ts, line 35 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mSktRjGsqO0y10xNp:-L26qQWAN-Tjd0uRThhP:b-rrad4o) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/TemplatedOperation.ts#L35)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Why do we need this collection here? 
</blockquote></details>

Implemented interface enforces it. Generally - all hydra resource can have links.

---

*[src/JsonLd/linksExtractor.ts, line 15 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mTZvhqE673wSg2nmP:-L26qYvSPVV2ZbaBPk2t:b-om83kp) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/JsonLd/linksExtractor.ts#L15)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> context

This is not a JSON-LD context, right? Could we use a different term?
</blockquote></details>

OK, to be changed

---

*[src/JsonLd/linksExtractor.ts, line 20 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mTqS5KcHwO9SmWBLE:-L26qad2aMQDuUjCpo_p:b-ttszcu) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/JsonLd/linksExtractor.ts#L20)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Why do you restrict this to the handful Hydra link relation types? Wouldn't it be simpler to treat everything the same way?
</blockquote></details>

The idea was to expose only hydra links. I wouldn't treat all relations as links. Indeed, client could dereference  related resources, but still I think these are relations, not links per se.

---

*[src/JsonLd/operationsExtractor.ts, line 6 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mUeBnQ_ke10Ja-S5U:-L26qruzj3QCqK3IAhfo:bo8lpk1) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/JsonLd/operationsExtractor.ts#L6)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> operationsExtractor

Doesn't seem to be a generic operations extractor. Should we rename to reflect what it does?
</blockquote></details>

OK, I'll think about better name.

---

*[tests/DataModel/TemplatedLink.spec.ts, line 19 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mVY03OgSUg0PBKwqy:-L26rZP02LcttaQMA-BS:b-x7s6oj) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/tests/DataModel/TemplatedLink.spec.ts#L19)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> hydra.Link, hydra.TemplatedLink

hydra:TemplatedLink is *not* a subclass of hydra:Link. In fact, they need to be disjoint classes as otherwise a client wouldn't know whether it should follow `@id` or `template`
</blockquote></details>

Hmm. OK, We'd need to amend the spec if these are disjoint classes!

---

*[tests/DataModel/Collections/LinksCollection.spec.ts, line 6 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mW3wi82wzm_WOW6iQ:-L26rp2ZzSyB4JON7GaF:b4oe1fg) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/tests/DataModel/Collections/LinksCollection.spec.ts#L6)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> iri: "LinkType1", type: [hydra.Link] 

Making this `type: "LinkType1"` or at least `relationType: "LinkType1"` would seem like a cleaner design to me. Also, since tests often double as documentation should we add the targets to these links?
</blockquote></details>

The `type` property contains what was available in `@type` (or empty collection if no `@type` was available at all). I believe you misunderstood this. As for adding `target` properties - these are not used in any way directly, thus I didn't want to add those.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-:-L26sCXHEi0PMemETPAL:b4n30yw)*

**Comment by alien-mcl** [comment]
I've added some tests related to nested resource. I hope this will cover your question.

---

Review status: 14 of 30 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/DataModel/ILink.ts, line 4 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mQvKk7CRx2EN-REi5:-L2Wl25mFgGS_H6JFLGH:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/ILink.ts#L4)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Yep, this is an incorrect description. There is no URI template available here at all.
</blockquote></details>

Done.

---

*[src/DataModel/ITemplatedOperation.ts, line 4 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mRLcF_3q24aoMXjOY:-L2Wl3GZtcyGBAn44nJc:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/ITemplatedOperation.ts#L4)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

OK, to be fixed.
</blockquote></details>

Done.

---

*[src/DataModel/TemplatedLink.ts, line 54 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mS0KCAQnW1gpA774q:-L2Wl5jX1OMeoumNL2dH:b-wjczot) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/TemplatedLink.ts#L54)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Not sure which part of the code is commented, but generally this is what you mentioned - static ILink compatible object with flat target. As for the _iri_ - again it is generanet from scratch as it is no more the original templated link.
</blockquote></details>

Can we acknowledge it?

---

*[src/DataModel/TemplatedOperation.ts, line 35 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mSktRjGsqO0y10xNp:-L2Wl8s9jAYkcuzwuAaO:b-mxylqe) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/TemplatedOperation.ts#L35)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Implemented interface enforces it. Generally - all hydra resource can have links.
</blockquote></details>

Can we acknowledge this one?

---

*[src/JsonLd/linksExtractor.ts, line 15 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mTZvhqE673wSg2nmP:-L2WlBnr68ua7lOfcgOB:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/JsonLd/linksExtractor.ts#L15)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

OK, to be changed
</blockquote></details>

Done.

---

*[src/JsonLd/linksExtractor.ts, line 20 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mTqS5KcHwO9SmWBLE:-L2WlGoYCovSJRpgHdNj:b-mxylqe) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/JsonLd/linksExtractor.ts#L20)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

The idea was to expose only hydra links. I wouldn't treat all relations as links. Indeed, client could dereference  related resources, but still I think these are relations, not links per se.
</blockquote></details>

Can we acknowledge this one?

---

*[src/JsonLd/memberTemplateOperationsExtractor.ts, line 6 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mUeBnQ_ke10Ja-S5U:-L2WlIwxbp6QhTKKUzDC:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/JsonLd/memberTemplateOperationsExtractor.ts#L6)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

OK, I'll think about better name.
</blockquote></details>

Done.

---

*[tests/DataModel/TemplatedLink.spec.ts, line 19 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mVY03OgSUg0PBKwqy:-L2WlRJjWa0MuZawe7JJ:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/tests/DataModel/TemplatedLink.spec.ts#L19)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Hmm. OK, We'd need to amend the spec if these are disjoint classes!
</blockquote></details>

Done.

---

*[tests/DataModel/Collections/LinksCollection.spec.ts, line 6 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mW3wi82wzm_WOW6iQ:-L2WlSyPXnlf1oaMINWW:b-74ak6l) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/tests/DataModel/Collections/LinksCollection.spec.ts#L6)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

The `type` property contains what was available in `@type` (or empty collection if no `@type` was available at all). I believe you misunderstood this. As for adding `target` properties - these are not used in any way directly, thus I didn't want to add those.
</blockquote></details>

I've revamped it a little to be more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-:-L2Wkx_dve3HW7HBrgwU:b-wwedtl)*

**Comment by lanthaler** [comment]
Yes, it does. Thanks. I like how this is coming together.

---

Reviewed 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/DataModel/TemplatedOperation.ts, line 35 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mSktRjGsqO0y10xNp:-L2aq2VkmJEazN9CYs1h:b-hfghm4) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/TemplatedOperation.ts#L35)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Can we acknowledge this one?
</blockquote></details>

Sounds good

---

*[src/JsonLd/linksExtractor.ts, line 20 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mTqS5KcHwO9SmWBLE:-L2aqFOefgokWqj2EZtP:b-xffz22) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/JsonLd/linksExtractor.ts#L20)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Can we acknowledge this one?
</blockquote></details>

I find that weird but let's move on and revisit this later

---

*[tests/DataModel/Collections/LinksCollection.spec.ts, line 6 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mW3wi82wzm_WOW6iQ:-L2aqzhR5SOBZmYBmriP:b-5mlhp1) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/tests/DataModel/Collections/LinksCollection.spec.ts#L6)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

I've revamped it a little to be more readable.
</blockquote></details>

I still find this confusing and think adding a target would make it easier to understand (a link needs to have a target by definition to be valid).

That beind said, [links have](https://tools.ietf.org/html/rfc8288#section-2) 
* a link context,
* a link relation type,
* a link target, and
* optionally, target attributes.

What you store in `iri` here is the link relation type. I think we should change that member name to make that clear. `iri` is highly ambiguous.

---

*[tests/JsonLd/JsonLdMetadataProvider.spec.ts, line 107 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L2at5k_MD3tJfD-SpL6:-L2at5k_MD3tJfD-SpL7:bfl6nwr) ([raw file](https://github.com/hydracg/heracles.ts/blob/96b6a50ccfef6656a41ac62cd91a938e792a096a/tests/JsonLd/JsonLdMetadataProvider.spec.ts#L107)):*
> .where(link => link.target.iri.match(/karol/))

Let's remove this, shouldn't be needed.

---

*[tests/JsonLd/nestedResourcesInput.json, line 15 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L2atTbnJG4bf-wUfYrF:-L2atTbnJG4bf-wUfYrG:b6agwl2) ([raw file](https://github.com/hydracg/heracles.ts/blob/96b6a50ccfef6656a41ac62cd91a938e792a096a/tests/JsonLd/nestedResourcesInput.json#L15)):*
> "@graph": {
>        "@id": "some:named.graph",

Let's also get rid of this named graph. It will just confuse people. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-:-L2au4yF2UWNX3LhGJ5N:b-o59qgq)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/DataModel/Collections/LinksCollection.spec.ts, line 6 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mW3wi82wzm_WOW6iQ:-L2b3q_X5N4KyzLY8Inz:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/tests/DataModel/Collections/LinksCollection.spec.ts#L6)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

I still find this confusing and think adding a target would make it easier to understand (a link needs to have a target by definition to be valid).

That beind said, [links have](https://tools.ietf.org/html/rfc8288#section-2) 
* a link context,
* a link relation type,
* a link target, and
* optionally, target attributes.

What you store in `iri` here is the link relation type. I think we should change that member name to make that clear. `iri` is highly ambiguous.
</blockquote></details>

Done.

---

*[tests/JsonLd/JsonLdMetadataProvider.spec.ts, line 107 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L2at5k_MD3tJfD-SpL6:-L2b3sLSQhHZdzqYJMQp:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/96b6a50ccfef6656a41ac62cd91a938e792a096a/tests/JsonLd/JsonLdMetadataProvider.spec.ts#L107)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> .where(link => link.target.iri.match(/karol/))

Let's remove this, shouldn't be needed.

</blockquote></details>

Done.

---

*[tests/JsonLd/nestedResourcesInput.json, line 15 at r2](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L2atTbnJG4bf-wUfYrF:-L2b3vT1FujeknZMbeOZ:b-896fix) ([raw file](https://github.com/hydracg/heracles.ts/blob/96b6a50ccfef6656a41ac62cd91a938e792a096a/tests/JsonLd/nestedResourcesInput.json#L15)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

> "@graph": {
>        "@id": "some:named.graph",

Let's also get rid of this named graph. It will just confuse people. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/23)*

**Comment by lanthaler** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/DataModel/TemplatedLink.ts, line 54 at r1](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-L1mS0KCAQnW1gpA774q:-L2fw3zb443cbUhtza_A:b-s6wt8t) ([raw file](https://github.com/hydracg/heracles.ts/blob/b79dba89dd025c6768307061d305c0bb48f41bde/src/DataModel/TemplatedLink.ts#L54)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Can we acknowledge it?
</blockquote></details>

Yeah, we don't need to block on this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hydracg/heracles.ts/23#-:-L2fwIll9OeOfqmYqcpL:bnfp4nl)*

**Pull request merged**
